-- Code Generated by Sidekick is for learning and experimentation purposes only.
DELIMITER //

CREATE PROCEDURE CancelOrder(IN ID INT)
BEGIN
    DELETE FROM Orders WHERE OrderID = ID;
    SELECT CONCAT('Order ', ID, ' is canceled') AS Confirmation;
END //

DELIMITER ;
CALL CancelOrder(5);