-- Code Generated by Sidekick is for learning and experimentation purposes only.
PREPARE GetOrderDetail FROM
'SELECT OrderID, Quantity, TotalCost FROM Orders WHERE CustomerID = ?';
-- Code Generated by Sidekick is for learning and experimentation purposes only.
SET @id = 1;
-- Code Generated by Sidekick is for learning and experimentation purposes only.
EXECUTE GetOrderDetail USING @id;
